apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      restartPolicy: Always
      containers:
      - name: fastapi
        image: raidsulin/fastapi-app:latest
        command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8002"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8002

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    name: 'http'
    port: 80
    targetPort: 8002
  type: LoadBalancer