apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      restartPolicy: Always
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      name: 'http'
      port: 27017
      targetPort: 27017
