apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-node-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-node-1
  template:
    metadata:
      labels:
        app: redis-node-1
    spec:
      restartPolicy: Always
      containers:
        - name: redis
          image: redis:latest
          command: ["redis-server", "--port", "7001", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000"]
          ports:
            - containerPort: 7001
          volumeMounts:
            - name: redis-data-1
              mountPath: /data
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: redis-data-1
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-node-1-service
spec:
  selector:
    app: redis-node-1
  ports:
    - protocol: TCP
      name: 'http'
      port: 7001
      targetPort: 7001
