name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Build Docker Image and Start Containers
        run: |
          docker-compose -f docker-compose.yaml build
          docker-compose -f docker-compose.yaml up -d

      - name: Wait for WebSocket service to be ready
        run: |
          docker-compose exec -T web /bin/bash -c "until nc -z localhost 8002; do sleep 1; done"

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q

      - name: Tear down Docker containers
        run: |
          docker-compose down