name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Install Dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - name: Create .env file from secrets
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      - name: Build Docker Image and Start Containers
        run: |
          docker-compose -f docker-compose.yaml build
          docker-compose -f docker-compose.yaml up -d

      - name: Debug Running Containers
        run: docker ps -a

      - name: Check WebSocket Logs
        run: docker-compose logs web

      - name: Wait for WebSocket inside Docker (Timeout 30s)
        run: |
          timeout 30 sh -c 'until nc -z 0.0.0.0 8002; do sleep 1; done' || (echo "WebSocket service failed to start!" && exit 1)

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q

      - name: Tear down Docker containers
        run: |
          docker-compose down
